/* ENUM UBICACION
AUTORES: JHONEYKER DELGADO, EMMANUEL VALENCIA, SIMON GUARIN, CAMILO MIRANDA Y JACOBO LEAL. */
package gestorAplicacion.hangar;

// CONTIENE LAS UNICAS TRES OPCIONES PARA LA UBICACION DE LAS SILLAS.
public enum Ubicacion {
	PASILLO,VENTANA,CENTRAL;
}
